user: openproject
group: openproject
targets:
  debian-7: &debian
    build_dependencies:
      - libmagickwand-dev
      - libsqlite3-dev
  ubuntu-14.04:
    <<: *debian
  fedora-20: &redhat
    build_dependencies:
      - ImageMagick-devel
  centos-6:
    <<: *redhat
before_precompile: "packaging/setup"
crons:
  - packaging/cron/openproject-clear-old-sessions
  - packaging/cron/openproject-create-svn-repositories
services:
  - postgres
installer: https://github.com/pkgr/installer.git#master
wizards:
  - https://github.com/pkgr/addon-legacy-installer.git#installer
  - https://github.com/pkgr/addon-mysql.git#installer
  - https://github.com/pkgr/addon-apache2.git#installer
  - https://github.com/pkgr/addon-svn-dav.git#installer
  - https://github.com/pkgr/addon-smtp.git#installer
  - https://github.com/pkgr/addon-memcached.git#installer
  - https://github.com/pkgr/addon-openproject.git#installer
buildpack: https://github.com/ddollar/heroku-buildpack-multi.git
